services:
  frontend:
    build:
      context: ./frontend
      target: prod
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=${RAILWAY_BACKEND_URL}/api
      - FRONTEND_URL=${RAILWAY_FRONTEND_URL}

  backend:
    build:
      context: ./backend
      target: prod
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
      - DATABASE_URL=${RAILWAY_DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - CHAPA_SECRET_KEY=${CHAPA_SECRET_KEY}
      - CHAPA_WEBHOOK_SECRET=${CHAPA_WEBHOOK_SECRET}
      - NGROK_URL=${RAILWAY_BACKEND_URL}
      - FRONTEND_URL=${RAILWAY_FRONTEND_URL}

volumes:
  next_cache:
